### ISSUE TITLE
Make Dijkstra test on TypeScript

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/typescript#2]
We have already implemented [Dijkstra's Algorithm](https://github.com/AllAlgorithms/typescript/blob/master/graphs/dijkstra/dijkstra.ts) in TypeScript but we need to add some test to it, can you help?

**Comment by seport** [comment]
I can help with this! How is the test suite run? I see that there's already some tests in the codebase. @abranhe

**Comment by elmarx** [comment]
Hey @seport,

Unfortunately there's no test-suite currently. I implemented an algorithm and used a simple script with assert (without any test-framework/test-runner). It does the job, so you might wanna give it a try: https://github.com/zauberpony/typescript/blob/add-factorial/math/factorial/factorial_iterative.test.ts

I execute these test-files via [ts-node](https://github.com/TypeStrong/ts-node).
